function i3help
    echo -e "\n=== i3 Window Manager - Useful Shortcuts ===\n"
    echo "Mod = Windows key (or Alt, depending on your config)"
    echo ""
    echo "Window Navigation:"
    echo "  Mod + h/j/k/l     → Move focus left/down/up/right"
    echo "  Mod + Arrow keys  → Same as above"
    echo ""
    echo "Move Windows:"
    echo "  Mod + Shift + h/j/k/l → Move window left/down/up/right"
    echo ""
    echo "Workspace Switching:"
    echo "  Mod + 1..9        → Switch to workspace 1 through 9"
    echo "  Mod + Shift + 1..9 → Move focused window to workspace 1 through 9"
    echo ""
    echo "Window Layouts:"
    echo "  Mod + s           → Stacking layout"
    echo "  Mod + w           → Tabbed layout"
    echo "  Mod + e           → Split (default tiling) layout"
    echo ""
    echo "Window Management:"
    echo "  Mod + Enter       → Open terminal"
    echo "  Mod + d           → App launcher (dmenu/rofi)"
    echo "  Mod + Shift + q   → Close focused window"
    echo ""
    echo "Resize Mode:"
    echo "  Mod + r           → Enter resize mode (use h/j/k/l or arrows to resize)"
    echo ""
    echo "Restart / Exit i3:"
    echo "  Mod + Shift + r   → Restart i3"
    echo "  Mod + Shift + e   → Exit i3 (logout)"
    echo ""
    echo "Floating Toggle:"
    echo "  Mod + Shift + Space → Toggle floating for focused window"
    echo ""
end
